// 솔루션 공통 데이터

// MAXY Mobile 슬라이드 이미지 목록
export const maxySlideImages = [
  'assets/images/reference/maxy/reference-thumbnail-047.png',
  'assets/images/reference/maxy/reference-thumbnail-048.png',
  'assets/images/reference/maxy/reference-thumbnail-049.png',
  'assets/images/reference/maxy/reference-thumbnail-051.png',
  'assets/images/reference/maxy/reference-thumbnail-053.png',
  'assets/images/reference/maxy/reference-thumbnail-054.png',
  'assets/images/reference/maxy/reference-thumbnail-055.png',
  'assets/images/reference/maxy/reference-thumbnail-059.png',
  'assets/images/reference/maxy/reference-thumbnail-062.png',
  'assets/images/reference/maxy/reference-thumbnail-066.png',
  'assets/images/reference/maxy/reference-thumbnail-072.png',
  'assets/images/reference/maxy/reference-thumbnail-074.png',
]

// MiAPS Hybrid 슬라이드 이미지 목록
export const miapsSlideImages = [
  'assets/images/reference/miaps/reference-thumbnail-050.png',
  'assets/images/reference/miaps/reference-thumbnail-052.png',
  'assets/images/reference/miaps/reference-thumbnail-056.png',
  'assets/images/reference/miaps/reference-thumbnail-058.png',
  'assets/images/reference/miaps/reference-thumbnail-060.png',
  'assets/images/reference/miaps/reference-thumbnail-061.png',
  'assets/images/reference/miaps/reference-thumbnail-063.png',
  'assets/images/reference/miaps/reference-thumbnail-064.png',
  'assets/images/reference/miaps/reference-thumbnail-078.png',
  'assets/images/reference/miaps/reference-thumbnail-079.png',
  'assets/images/reference/miaps/reference-thumbnail-081.png',
  'assets/images/reference/miaps/reference-thumbnail-082.png',
  'assets/images/reference/miaps/reference-thumbnail-083.png',
  'assets/images/reference/miaps/reference-thumbnail-084.png',
  'assets/images/reference/miaps/reference-thumbnail-086.png',
  'assets/images/reference/miaps/reference-thumbnail-088.png',
  'assets/images/reference/miaps/reference-thumbnail-090.png',
  'assets/images/reference/miaps/reference-thumbnail-091.png',
  'assets/images/reference/miaps/reference-thumbnail-092.png',
  'assets/images/reference/miaps/reference-thumbnail-093.png',
  'assets/images/reference/miaps/reference-thumbnail-094.png',
  'assets/images/reference/miaps/reference-thumbnail-099.png',
  'assets/images/reference/miaps/reference-thumbnail-100.png',
  'assets/images/reference/miaps/reference-thumbnail-101.png',
  'assets/images/reference/miaps/reference-thumbnail-102.png',
  'assets/images/reference/miaps/reference-thumbnail-103.png',
  'assets/images/reference/miaps/reference-thumbnail-105.png',
  'assets/images/reference/miaps/reference-thumbnail-106.png',
  'assets/images/reference/miaps/reference-thumbnail-108.png',
  'assets/images/reference/miaps/reference-thumbnail-109.png',
  'assets/images/reference/miaps/reference-thumbnail-110.png',
  'assets/images/reference/miaps/reference-thumbnail-112.png',
  'assets/images/reference/miaps/reference-thumbnail-113.png',
  'assets/images/reference/miaps/reference-thumbnail-114.png',
  'assets/images/reference/miaps/reference-thumbnail-115.png',
  'assets/images/reference/miaps/reference-thumbnail-117.png',
  'assets/images/reference/miaps/reference-thumbnail-118.png',
  'assets/images/reference/miaps/reference-thumbnail-119.png',
  'assets/images/reference/miaps/reference-thumbnail-121.png',
  'assets/images/reference/miaps/reference-thumbnail-123.png',
  'assets/images/reference/miaps/reference-thumbnail-124.png',
  'assets/images/reference/miaps/reference-thumbnail-125.png',
  'assets/images/reference/miaps/reference-thumbnail-127.png',
  'assets/images/reference/miaps/reference-thumbnail-128.png',
  'assets/images/reference/miaps/reference-thumbnail-129.png',
  'assets/images/reference/miaps/reference-thumbnail-132.png',
  'assets/images/reference/miaps/reference-thumbnail-133.png',
  'assets/images/reference/miaps/reference-thumbnail-134.png',
]

